### PR TITLE
lagoon labels pods in openshift with `services` label

### PR DESCRIPTION
**Pull request by Schnitzel**

### CODE REVIEW

**Comment by Schnitzel** [comment]
build and pushed this as `amazeeio/lagoon-builddeploy:v0.1.7-rc1`

**Comment by shreddedbacon** [comment]
Are we eventually going to transition to using `lagoon.sh/X` for labels?

**Comment by Schnitzel** [comment]
@shreddedbacon yes we did already for k8s deployments, for openshift deployments I'm not sure, as my hope with openshift 4 is anyway that we can use the k8s deployment system and don't need the openshift deployment way at all anymore :)

**Comment by shreddedbacon** [comment]
I think this will be fine to merge, but where else do we use this label selector? 

If possible, being able to change other things or run a script that will update existing labels to the new ones may be better?

**Comment by Schnitzel** [comment]
@shreddedbacon I though about this too, but we would need to change the labels of all running pods which means we have to change also the labels of the deploymentconfigs which will cause a redeployment. So I don't think that's really feasible.

**Comment by Schnitzel** [comment]
oh and it's actually used by the deploymentconfig to know which pods it's controlling: https://github.com/amazeeio/lagoon/blob/master/images/oc-build-deploy-dind/openshift-templates/nginx/deployment.yml#L62

so changing this would be even harder as the label is used by openshift to know which pods it started, etc.

**Comment by shreddedbacon** [comment]
Bugger. Will merge then

**Pull request merged**
