### PR TITLE
Additional Harbor credential fixes

### LINKED ISSUE #57: Controller injects wrong harbor credentials into container
with the recent fix to append harbor credentials instead of replacing them: https://github.com/amazeeio/lagoon-kbd/pull/56
there is now a possibility that the controller injects the wrong credentials into the build container:
https://github.com/amazeeio/lagoon-kbd/blob/12419865e6ffc971d73befcc2b251420303b781f/controllers/lagoonbuild_controller.go#L451-L462
basically the code above loads the registries defined in the `lagoon-internal-registry-secret` secret and injects them into the docker container. If there are multiple registries defined in the `lagoon-internal-registry-secret` secret (like it can happen now) it's possible that the wrong registry is injected.

We probably should filter for the actual defined harbor registry to the controller and only inject that one into the build pods

### LINKED ISSUE #58: recreate lagoon-internal-registry-secret secret if it does not exist
during debugging and trying to find a workaround for https://github.com/amazeeio/lagoon-kbd/issues/57 I found that if:
1. the secret `lagoon-internal-registry-secret` does not exist
2. the robot account in harbor is still valid (not deleted, not expired yet) 
then:
- `CreateOrRefreshRobot` returns `nil` and the following code:
https://github.com/amazeeio/lagoon-kbd/blob/12419865e6ffc971d73befcc2b251420303b781f/controllers/lagoonbuild_controller.go#L945-L962
- does not upsert the secret
the only way to create the secret again is to delete the robot account in harbor which is a bit confusing.

I think we should always upsert the image with the robot account, but I guess this might not be possible as we cannot get the token anymore from harbor after the robot account was created.
So maybe we need to check if the `lagoon-internal-registry-secret` does not exist, that we forcefully recreate the robot account?

### PR DESCRIPTION
**Pull request by shreddedbacon**
closes #57 
closes #58

### CODE REVIEW

**Comment by Schnitzel** [comment]
@shreddedbacon I built and pushed the image here: `amazeeio/lagoon-builddeploy:pr59`
unfortunately during testing I think I found an issue with the domains.

When I deleted the secret and let it recreate it created it with `harbor.us2.amazee.io` (no scheme), but `r.Harbor.URL` is with `https://harbor.us2.amazee.io` and so the matching doesn't work anymore and so no secret is injected into the build pod.

Maybe we need to do some url parsing and matching?

**Comment by Schnitzel** [comment]
oh actually I think I found the issue: the controller creates the `.dockerconfigjson` with `https://harbor.us2.amazee.io` but then during the lagoon deployment it updates the secret:
https://github.com/amazeeio/lagoon/blob/97a59c6211aea76d6a466c619043d429154fe6d4/images/kubectl-build-deploy-dind/build-deploy.sh#L62
which then stores it without the scheme.

**Comment by Schnitzel** [comment]
so I think changing the kubectl-build-deploy-dind image will be hard as we have different versions running.
Could we instead check with and without the schema here: https://github.com/amazeeio/lagoon-kbd/pull/59/files#diff-2c7ab529e4f550c2ff3aee023fd193b42d257ed8c1b37793613ee2917295ac9aR456 ?

**Comment by Schnitzel** [comment]
after some more testing I tried with `--harbor-url=harbor.us2.amazee.io`
while technically this works, there is now the issue that some `lagoon-internal-registry-secret` secrets have `https://harbor.us2.amazee.io` inside of them and then the deployments fail, as the controller does not see the harbor url matching and does not inject a secret at all.
I think we still need to do the schema parsing as it's safer (also then it doesn't really matter if `--harbor-url` has a schema or not)

**Comment by shreddedbacon** [comment]
I forgot that the build image updates this secret too, that makes this annoying.

As the controller will try and create all the secrets with the `--harbor-url` flag version, but then the build is now updating this to be the hostname only.

Are image pull secrets smart enough to know if `https://harbor.us2.amazee.io` and `harbor.us2.amazee.io` are the same in terms of being able to pull images from?
Say the build ran and tagged/pushed `harbor.us2.amazee.io/project/environment/image`, and then the image secret gets updated to be `harbor.us2.amazee.io` as the URL.

If the robot credential rotation occurs, it will re-create the secret with `https://harbor.us2.amazee.io` as the URL now, will this break an image pull for this image then `harbor.us2.amazee.io/project/environment/image`?

**Pull request merged**
